name: cmis-notebook
dependencies:
  - python=3.13
  - ipykernel
  - ipympl
  - ipyleaflet
  - matplotlib
  - meshplot
  - wildmeshing
  - ipywidgets
  - scipy
  - numpy
  - igl
channels:
  - conda-forge
