name: geo-notebook
dependencies:
   - arrow
   - autopep8
   - bokeh
   - bqplot
   - cartopy
   - cdo
   - cftime
   - click
   - cmocean
   - colorcet
   - cython 
   - cytoolz
   - dask
   - dask-ml
   - dask-tensorflow
   - datashader
   - distributed
   - eofs
   - esmpy
   - fastparquet
   - flake8
   - gdal
   - geoviews
   - graphviz
   - gsw
   - hvplot
   - iris
   - jedi
   - libsodium
   - lmfit
   - lz4
   - msgpack-python
   - nb_conda_kernels
   - nco
   - nc-time-axis
   - netcdf4
   - nodejs
   - nomkl
   - numba
   - numcodecs
   - numpy
   - palettable
   - pandas
   - pyarrow
   - panel
   - plotly
   - python-blosc
   - python-graphviz
   - rasterio
   - scikit-image
   - scikit-learn
   - scipy
   - seaborn
   - statsmodels
   - toolz
   - tornado
   - xarray
   - xesmf
   - zarr
   - zict
